const RoomBookingslots = [
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":12,"minute":30,"nano":0,"second":0},"status":"A","timeSlot":{"hour":12,"minute":0,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":13,"minute":0,"nano":0,"second":0},"status":"A","timeSlot":{"hour":12,"minute":30,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":18,"minute":20,"nano":0,"second":0},"status":"A","timeSlot":{"hour":13,"minute":0,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":18,"minute":25,"nano":0,"second":0},"status":"A","timeSlot":{"hour":13,"minute":30,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":18,"minute":30,"nano":0,"second":0},"status":"A","timeSlot":{"hour":14,"minute":0,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":18,"minute":40,"nano":0,"second":0},"status":"A","timeSlot":{"hour":14,"minute":30,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":18,"minute":45,"nano":0,"second":0},"status":"A","timeSlot":{"hour":15,"minute":0,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":18,"minute":50,"nano":0,"second":0},"status":"A","timeSlot":{"hour":15,"minute":30,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":18,"minute":55,"nano":0,"second":0},"status":"A","timeSlot":{"hour":16,"minute":0,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":19,"minute":0,"nano":0,"second":0},"status":"A","timeSlot":{"hour":16,"minute":30,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":19,"minute":5,"nano":0,"second":0},"status":"A","timeSlot":{"hour":17,"minute":0,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":19,"minute":10,"nano":0,"second":0},"status":"A","timeSlot":{"hour":17,"minute":30,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":19,"minute":15,"nano":0,"second":0},"status":"A","timeSlot":{"hour":18,"minute":0,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":19,"minute":20,"nano":0,"second":0},"status":"A","timeSlot":{"hour":18,"minute":30,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":19,"minute":25,"nano":0,"second":0},"status":"A","timeSlot":{"hour":19,"minute":0,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":19,"minute":30,"nano":0,"second":0},"status":"A","timeSlot":{"hour":19,"minute":30,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":19,"minute":35,"nano":0,"second":0},"status":"A","timeSlot":{"hour":20,"minute":0,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":19,"minute":40,"nano":0,"second":0},"status":"A","timeSlot":{"hour":20,"minute":30,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":19,"minute":45,"nano":0,"second":0},"status":"A","timeSlot":{"hour":21,"minute":0,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":19,"minute":50,"nano":0,"second":0},"status":"A","timeSlot":{"hour":21,"minute":30,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":19,"minute":55,"nano":0,"second":0},"status":"A","timeSlot":{"hour":22,"minute":0,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":20,"minute":0,"nano":0,"second":0},"status":"A","timeSlot":{"hour":22,"minute":30,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":20,"minute":5,"nano":0,"second":0},"status":"A","timeSlot":{"hour":23,"minute":0,"nano":0,"second":0}},
    {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":20,"minute":10,"nano":0,"second":0},"status":"A","timeSlot":{"hour":23,"minute":30,"nano":0,"second":0}},
    // {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":20,"minute":15,"nano":0,"second":0},"status":"A","timeSlot":{"hour":24,"minute":0,"nano":0,"second":0}},
    // {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":20,"minute":20,"nano":0,"second":0},"status":"A","timeSlot":{"hour":24,"minute":,"nano":0,"second":0}},
    // {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":20,"minute":25,"nano":0,"second":0},"status":"A","timeSlot":{"hour":20,"minute":20,"nano":0,"second":0}},
    // {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":20,"minute":30,"nano":0,"second":0},"status":"A","timeSlot":{"hour":20,"minute":25,"nano":0,"second":0}},
    // {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":20,"minute":35,"nano":0,"second":0},"status":"A","timeSlot":{"hour":20,"minute":30,"nano":0,"second":0}},
    // {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":20,"minute":40,"nano":0,"second":0},"status":"A","timeSlot":{"hour":20,"minute":35,"nano":0,"second":0}},
    // {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":20,"minute":45,"nano":0,"second":0},"status":"A","timeSlot":{"hour":20,"minute":40,"nano":0,"second":0}},
    // {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":20,"minute":50,"nano":0,"second":0},"status":"A","timeSlot":{"hour":20,"minute":45,"nano":0,"second":0}},
    // {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":20,"minute":55,"nano":0,"second":0},"status":"A","timeSlot":{"hour":20,"minute":50,"nano":0,"second":0}},
    // {"applicationId":1,"doctorLocalId":52,"ellapseStatus":"N","endTimeSlot":{"hour":21,"minute":0,"nano":0,"second":0},"status":"A","timeSlot":{"hour":20,"minute":55,"nano":0,"second":0}}
  ];
  
  export default RoomBookingslots;
  